CREATE TABLE Devices (
  Id CHAR(36) NOT NULL PRIMARY KEY,
  SerialNumber VARCHAR(64) NOT NULL UNIQUE,
  DeviceTypeId CHAR(36) NOT NULL,
  Status VARCHAR(32) NOT NULL,
  CurrentLocationId CHAR(36) NULL,
  CreatedAtUtc DATETIME NOT NULL
);

CREATE TABLE Locations (
  Id CHAR(36) NOT NULL PRIMARY KEY,
  Name VARCHAR(128) NOT NULL UNIQUE,
  ParentId CHAR(36) NULL,
  IsActive TINYINT(1) NOT NULL DEFAULT 1
);
