
build:
	gcc main.c -o main
	clear
	./main < input.txt
	./main < input2.txt
	./main < input3.txt
	./main < input4.txt
	./main < input5.txt

git:
	git add .
	git commit -m "zjednoduseni mainu"
	git push -u origin main