-- Generated by Oracle SQL Developer Data Modeler 20.3.0.283.0710
--   at:        2021-11-19 05:26:33 CET
--   site:      Oracle Database 21c
--   type:      Oracle Database 21c



-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

CREATE TABLE account (
    account_id   INTEGER NOT NULL,
    a_number     INTEGER NOT NULL,
    bank_code    INTEGER NOT NULL,
    last_update  TIMESTAMP NOT NULL
);

ALTER TABLE account ADD CONSTRAINT account_pk PRIMARY KEY ( account_id );

CREATE TABLE address (
    address_id  INTEGER NOT NULL,
    city_id     INTEGER NOT NULL,
    street      VARCHAR2(50) NOT NULL,
    "Number"    INTEGER NOT NULL
);

ALTER TABLE address ADD CONSTRAINT address_pk PRIMARY KEY ( address_id );

CREATE TABLE city (
    city_id     INTEGER NOT NULL,
    name        VARCHAR2(50) NOT NULL,
    postcode    INTEGER NOT NULL,
    country_id  INTEGER NOT NULL
);

ALTER TABLE city ADD CONSTRAINT city_pk PRIMARY KEY ( city_id );

CREATE TABLE country (
    country_id  INTEGER NOT NULL,
    name        VARCHAR2(50) NOT NULL
);

ALTER TABLE country ADD CONSTRAINT country_pk PRIMARY KEY ( country_id );

CREATE TABLE disclass (
    classod      INTEGER NOT NULL,
    description  VARCHAR2(100) NOT NULL,
    last_update  TIMESTAMP NOT NULL
);

ALTER TABLE disclass ADD CONSTRAINT disclass_pk PRIMARY KEY ( classod );

CREATE TABLE dl (
    dl_choices   INTEGER NOT NULL,
    description  VARCHAR2(50) NOT NULL,
    last_update  TIMESTAMP NOT NULL
);

ALTER TABLE dl ADD CONSTRAINT dl_pk PRIMARY KEY ( dl_choices );

CREATE TABLE education (
    education_id  INTEGER NOT NULL,
    description   VARCHAR2(50) NOT NULL,
    last_update   TIMESTAMP NOT NULL
);

ALTER TABLE education ADD CONSTRAINT education_pk PRIMARY KEY ( education_id );

CREATE TABLE employee (
    employee_id   INTEGER NOT NULL,
    name          VARCHAR2(20) NOT NULL,
    surname       VARCHAR2(20) NOT NULL,
    phone         VARCHAR2(20) NOT NULL,
    email         VARCHAR2(30) NOT NULL,
    dob           DATE NOT NULL,
    bn            VARCHAR2(11) NOT NULL,
    jobdesc       VARCHAR2(20) NOT NULL,
    "User"        NUMBER NOT NULL,
    login         VARCHAR2(10),
    boemployment  DATE NOT NULL,
    eoemployment  DATE,
    record_date   TIMESTAMP NOT NULL,
    manager_id    INTEGER
);

ALTER TABLE employee ADD CONSTRAINT employee_ck_1 CHECK ( boemployment <= eoemployment );

ALTER TABLE employee ADD CONSTRAINT employee_pk PRIMARY KEY ( employee_id );

CREATE TABLE employee_address (
    employee_id  INTEGER NOT NULL,
    address_id   INTEGER NOT NULL
);

ALTER TABLE employee_address ADD CONSTRAINT employee_address_pk PRIMARY KEY ( employee_id,
                                                                              address_id );

CREATE TABLE factor (
    factor_id    INTEGER NOT NULL,
    factor_name  VARCHAR2(50) NOT NULL,
    last_update  TIMESTAMP NOT NULL
);

ALTER TABLE factor ADD CONSTRAINT factor_pk PRIMARY KEY ( factor_id );

CREATE TABLE factors (
    rof               INTEGER NOT NULL,
    last_measurement  DATE NOT NULL,
    frequency         INTEGER NOT NULL,
    nextmeasurement   DATE,
    record_date       DATE NOT NULL,
    employee_id       INTEGER NOT NULL,
    factor_id         INTEGER NOT NULL
);

ALTER TABLE factors ADD CONSTRAINT factors_ck_1 CHECK ( last_measurement < nextmeasurement );

ALTER TABLE factors ADD CONSTRAINT factors_pk PRIMARY KEY ( rof );

CREATE TABLE "CHECK" (
    check_id     INTEGER NOT NULL,
    check_name   VARCHAR2(40) NOT NULL,
    frequency    INTEGER NOT NULL,
    last_update  TIMESTAMP NOT NULL
);

ALTER TABLE "CHECK" ADD CONSTRAINT check_pk PRIMARY KEY ( check_id );

CREATE TABLE checks (
    roch_id      INTEGER NOT NULL,
    check_date   DATE NOT NULL,
    check_end    DATE,
    expiration   DATE NOT NULL,
    "Update"     DATE NOT NULL,
    check_id     INTEGER NOT NULL,
    employee_id  INTEGER NOT NULL
);

ALTER TABLE checks ADD CONSTRAINT checks_ck_1 CHECK ( check_end >= check_date );

ALTER TABLE checks ADD CONSTRAINT checks_pk PRIMARY KEY ( roch_id );

CREATE TABLE manager (
    employee_id      INTEGER NOT NULL,
    pool_car         NUMBER NOT NULL,
    department       VARCHAR2(50),
    global_position  NUMBER NOT NULL,
    nfs              INTEGER NOT NULL
);

ALTER TABLE manager ADD CONSTRAINT manager_pk PRIMARY KEY ( employee_id );

CREATE TABLE marital_status (
    marital_id   INTEGER NOT NULL,
    description  VARCHAR2(50) NOT NULL,
    last_update  TIMESTAMP NOT NULL
);

ALTER TABLE marital_status ADD CONSTRAINT marital_status_pk PRIMARY KEY ( marital_id );

CREATE TABLE methods (
    m_id         INTEGER NOT NULL,
    mail         NUMBER,
    cash         NUMBER,
    last_update  TIMESTAMP NOT NULL
);

ALTER TABLE methods ADD CONSTRAINT methods_pk PRIMARY KEY ( m_id );

CREATE TABLE payments (
    p_id         INTEGER NOT NULL,
    category     INTEGER NOT NULL,
    bonus        INTEGER NOT NULL,
    m_id         INTEGER,
    account_id   INTEGER,
    last_update  TIMESTAMP NOT NULL,
    employee_id  INTEGER NOT NULL
);

ALTER TABLE payments
    ADD CONSTRAINT arc_2 CHECK ( ( ( account_id IS NOT NULL )
                                   AND ( m_id IS NULL ) )
                                 OR ( ( m_id IS NOT NULL )
                                      AND ( account_id IS NULL ) ) );

ALTER TABLE payments ADD CONSTRAINT payments_pk PRIMARY KEY ( p_id );

CREATE TABLE pi (
    pi_id           INTEGER NOT NULL,
    id_number       INTEGER NOT NULL,
    dl_number       INTEGER NOT NULL,
    marital_status  NUMBER NOT NULL,
    photo           BLOB,
    noochildren     INTEGER NOT NULL,
    disability      NUMBER NOT NULL,
    hobbies         VARCHAR2(50),
    record_date     TIMESTAMP NOT NULL,
    classod         INTEGER NOT NULL,
    marital_id      INTEGER NOT NULL,
    education_id    INTEGER NOT NULL,
    dl_choices      INTEGER NOT NULL,
    employee_id     INTEGER NOT NULL
);

ALTER TABLE pi ADD CONSTRAINT pi_pk PRIMARY KEY ( pi_id );

CREATE TABLE ppe (
    ppe_id       INTEGER NOT NULL,
    ppe_name     VARCHAR2(20) NOT NULL,
    last_update  TIMESTAMP NOT NULL
);

ALTER TABLE ppe ADD CONSTRAINT ppe_pk PRIMARY KEY ( ppe_id );

CREATE TABLE ppes (
    provision_id  INTEGER NOT NULL,
    receive       DATE NOT NULL,
    exchange      DATE NOT NULL,
    training      NUMBER NOT NULL,
    ppe_id        INTEGER NOT NULL,
    employee_id   INTEGER NOT NULL
);

ALTER TABLE ppes ADD CONSTRAINT ppes_ck_1 CHECK ( exchange >= receive );

ALTER TABLE ppes ADD CONSTRAINT ppes_pk PRIMARY KEY ( provision_id );

CREATE TABLE salary_change (
    date_modified  DATE NOT NULL,
    salary         INTEGER NOT NULL,
    old_salary     INTEGER,
    modified_by    VARCHAR2(50),
    employee_id    INTEGER NOT NULL
);

ALTER TABLE salary_change ADD CONSTRAINT salary_change_pk PRIMARY KEY ( date_modified,
                                                                        employee_id );

CREATE TABLE sickness (
    sick_id      INTEGER NOT NULL,
    sick         NUMBER NOT NULL,
    sicknesss    DATE,
    sicknesse    DATE,
    hospital     NUMBER NOT NULL,
    hospitals    DATE,
    hospitale    DATE,
    noosds       INTEGER NOT NULL,
    record_date  TIMESTAMP(0) NOT NULL,
    employee_id  INTEGER NOT NULL
);

ALTER TABLE sickness ADD CONSTRAINT sickness_ck_1 CHECK ( sicknesss <= sicknesse );

ALTER TABLE sickness ADD CONSTRAINT sickness_ck_2 CHECK ( hospitals <= hospitale );

ALTER TABLE sickness ADD CONSTRAINT sickness_pk PRIMARY KEY ( sick_id );

CREATE TABLE training (
    training_id    INTEGER NOT NULL,
    training_name  VARCHAR2(50) NOT NULL,
    frequency      INTEGER NOT NULL,
    last_update    TIMESTAMP NOT NULL
);

ALTER TABLE training ADD CONSTRAINT training_pk PRIMARY KEY ( training_id );

CREATE TABLE training_history (
    employee_id     INTEGER NOT NULL,
    training_start  DATE NOT NULL,
    training_end    DATE,
    place           VARCHAR2(50) NOT NULL,
    expiration      DATE NOT NULL,
    training_id     INTEGER NOT NULL
);

ALTER TABLE training_history ADD CONSTRAINT training_history_ck_1 CHECK ( training_start <= training_end );

ALTER TABLE training_history ADD CONSTRAINT training_history_ck_2 CHECK ( training_start < expiration );

ALTER TABLE training_history ADD CONSTRAINT training_history_ck_3 CHECK ( training_end < expiration );

ALTER TABLE training_history
    ADD CONSTRAINT training_history_pk PRIMARY KEY ( training_start,
                                                     training_id,
                                                     employee_id );

CREATE TABLE whours (
    record_date  DATE NOT NULL,
    holiday      INTEGER NOT NULL,
    arrival      DATE NOT NULL,
    leaving      DATE,
    shiftb       DATE NOT NULL,
    shifte       DATE NOT NULL,
    employee_id  INTEGER NOT NULL
);

ALTER TABLE whours ADD CONSTRAINT whours_pk PRIMARY KEY ( record_date,
                                                          employee_id );

CREATE TABLE worker (
    employee_id   INTEGER NOT NULL,
    category_id   INTEGER NOT NULL,
    white_collar  NUMBER NOT NULL
);

ALTER TABLE worker ADD CONSTRAINT worker_pk PRIMARY KEY ( employee_id );

ALTER TABLE address
    ADD CONSTRAINT address_city_fk FOREIGN KEY ( city_id )
        REFERENCES city ( city_id );

ALTER TABLE city
    ADD CONSTRAINT city_country_fk FOREIGN KEY ( country_id )
        REFERENCES country ( country_id );

ALTER TABLE employee_address
    ADD CONSTRAINT employee_address_address_fk FOREIGN KEY ( address_id )
        REFERENCES address ( address_id );

ALTER TABLE employee_address
    ADD CONSTRAINT employee_address_employee_fk FOREIGN KEY ( employee_id )
        REFERENCES employee ( employee_id );

ALTER TABLE employee
    ADD CONSTRAINT employee_employee_fk FOREIGN KEY ( manager_id )
        REFERENCES employee ( employee_id );

ALTER TABLE factors
    ADD CONSTRAINT factors_employee_fk FOREIGN KEY ( employee_id )
        REFERENCES employee ( employee_id );

ALTER TABLE factors
    ADD CONSTRAINT factors_factor_fk FOREIGN KEY ( factor_id )
        REFERENCES factor ( factor_id );

ALTER TABLE checks
    ADD CONSTRAINT checks_employee_fk FOREIGN KEY ( employee_id )
        REFERENCES employee ( employee_id );

ALTER TABLE checks
    ADD CONSTRAINT checks_check_fk FOREIGN KEY ( check_id )
        REFERENCES "CHECK" ( check_id );

ALTER TABLE manager
    ADD CONSTRAINT manager_employee_fk FOREIGN KEY ( employee_id )
        REFERENCES employee ( employee_id );

ALTER TABLE payments
    ADD CONSTRAINT payments_account_fk FOREIGN KEY ( account_id )
        REFERENCES account ( account_id );

ALTER TABLE payments
    ADD CONSTRAINT payments_employee_fk FOREIGN KEY ( employee_id )
        REFERENCES employee ( employee_id );

ALTER TABLE payments
    ADD CONSTRAINT payments_methods_fk FOREIGN KEY ( m_id )
        REFERENCES methods ( m_id );

ALTER TABLE pi
    ADD CONSTRAINT pi_disclass_fk FOREIGN KEY ( classod )
        REFERENCES disclass ( classod );

ALTER TABLE pi
    ADD CONSTRAINT pi_dl_fk FOREIGN KEY ( dl_choices )
        REFERENCES dl ( dl_choices );

ALTER TABLE pi
    ADD CONSTRAINT pi_education_fk FOREIGN KEY ( education_id )
        REFERENCES education ( education_id );

ALTER TABLE pi
    ADD CONSTRAINT pi_employee_fk FOREIGN KEY ( employee_id )
        REFERENCES employee ( employee_id );

ALTER TABLE pi
    ADD CONSTRAINT pi_marital_status_fk FOREIGN KEY ( marital_id )
        REFERENCES marital_status ( marital_id );

ALTER TABLE ppes
    ADD CONSTRAINT ppes_employee_fk FOREIGN KEY ( employee_id )
        REFERENCES employee ( employee_id );

ALTER TABLE ppes
    ADD CONSTRAINT ppes_ppe_fk FOREIGN KEY ( ppe_id )
        REFERENCES ppe ( ppe_id );

ALTER TABLE salary_change
    ADD CONSTRAINT salary_change_employee_fk FOREIGN KEY ( employee_id )
        REFERENCES employee ( employee_id );

ALTER TABLE sickness
    ADD CONSTRAINT sickness_employee_fk FOREIGN KEY ( employee_id )
        REFERENCES employee ( employee_id );

ALTER TABLE training_history
    ADD CONSTRAINT training_history_employee_fk FOREIGN KEY ( employee_id )
        REFERENCES employee ( employee_id );

ALTER TABLE training_history
    ADD CONSTRAINT training_history_training_fk FOREIGN KEY ( training_id )
        REFERENCES training ( training_id );

ALTER TABLE whours
    ADD CONSTRAINT whours_employee_fk FOREIGN KEY ( employee_id )
        REFERENCES employee ( employee_id );

ALTER TABLE worker
    ADD CONSTRAINT worker_employee_fk FOREIGN KEY ( employee_id )
        REFERENCES employee ( employee_id );

CREATE OR REPLACE TRIGGER fkntm_factors BEFORE
    UPDATE OF employee_id ON factors
BEGIN
    raise_application_error(-20225, 'Non Transferable FK constraint  on table FACTORS is violated');
END;
/

CREATE OR REPLACE TRIGGER fkntm_checks BEFORE
    UPDATE OF employee_id ON checks
BEGIN
    raise_application_error(-20225, 'Non Transferable FK constraint  on table CHECKS is violated');
END;
/

CREATE OR REPLACE TRIGGER fkntm_payments BEFORE
    UPDATE OF employee_id ON payments
BEGIN
    raise_application_error(-20225, 'Non Transferable FK constraint  on table PAYMENTS is violated');
END;
/

CREATE OR REPLACE TRIGGER fkntm_pi BEFORE
    UPDATE OF employee_id ON pi
BEGIN
    raise_application_error(-20225, 'Non Transferable FK constraint  on table PI is violated');
END;
/

CREATE OR REPLACE TRIGGER fkntm_ppes BEFORE
    UPDATE OF employee_id ON ppes
BEGIN
    raise_application_error(-20225, 'Non Transferable FK constraint  on table PPES is violated');
END;
/

CREATE OR REPLACE TRIGGER fkntm_salary_change BEFORE
    UPDATE OF employee_id ON salary_change
BEGIN
    raise_application_error(-20225, 'Non Transferable FK constraint  on table SALARY_CHANGE is violated');
END;
/

CREATE OR REPLACE TRIGGER fkntm_sickness BEFORE
    UPDATE OF employee_id ON sickness
BEGIN
    raise_application_error(-20225, 'Non Transferable FK constraint  on table SICKNESS is violated');
END;
/

CREATE OR REPLACE TRIGGER fkntm_training_history BEFORE
    UPDATE OF employee_id ON training_history
BEGIN
    raise_application_error(-20225, 'Non Transferable FK constraint  on table TRAINING_HISTORY is violated');
END;
/

CREATE OR REPLACE TRIGGER fkntm_whours BEFORE
    UPDATE OF employee_id ON whours
BEGIN
    raise_application_error(-20225, 'Non Transferable FK constraint  on table WHOURS is violated');
END;
/

--  ERROR: No Discriminator Column found in Arc FKArc_3 - constraint trigger for Arc cannot be generated 

--  ERROR: No Discriminator Column found in Arc FKArc_3 - constraint trigger for Arc cannot be generated



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                            26
-- CREATE INDEX                             0
-- ALTER TABLE                             62
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           9
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   2
-- WARNINGS                                 0
