# Generated by Django 5.1.6 on 2025-04-09 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_positions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='employee',
        ),
        migrations.AlterField(
            model_name='reservation',
            name='creation_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
