# Generated by Django 5.2 on 2025-05-14 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_guest_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='employee',
        ),
    ]
