# Generated by Django 5.2 on 2025-05-14 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_remove_reservation_employee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicepricehistory',
            name='service',
        ),
        migrations.AddField(
            model_name='service',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.DeleteModel(
            name='RoomTypePriceHistory',
        ),
        migrations.DeleteModel(
            name='ServicePriceHistory',
        ),
    ]
